Paginating kaminari
NaldoColella/crud-municipe pull request #2
Opened 2021-05-05 19:59 UTC by NaldoColella

BE
Adding gem
Adjusting get/ municipes
Serializing results
Logic to getAll if both params not set (page, per_page)

FE
Refactor to start using api for paginate instead of getting all
minor baseUrl axios

2021-05-05 20:10 UTC, ricardopacheco requested changes

2021-05-05 20:10 UTC, ricardopacheco commented on back-end-api/Gemfile
> +gem 'kaminari'
No Gemfile, você precisa definir as versões específicas que são usadas. O padrão mais usado é `at least`. Exemplo:

gem `rails`, `~> 6.0`. Isso garante que a versão mínima deve ser a 6.0. No caso, o gemfile.lock salvou a kaminari abaixo com a `1.2.1`. Faça isso em todas as gems do Gemfile e use como base o Gemfile.lock

2021-05-05 20:10 UTC, ricardopacheco commented on back-end-api/app/controllers/municipes_controller.rb
>      @totalMunicipes = Municipe.count;
; é coisa de javascript :trollface: 

Remove isso

2021-05-05 20:10 UTC, ricardopacheco commented on back-end-api/app/controllers/municipes_controller.rb
> +    @municipes = checkPaginateParams(params) ? getPaginatedResults(params) : getAllResults()
(sugestão): Model.all.page(params[:page] || 1).per_page(params[:per_page] || 10) fica bem mais elegante

2021-05-05 20:10 UTC, ricardopacheco commented on back-end-api/app/controllers/municipes_controller.rb
> +      items.map{ |item| MunicipeSerializer.new(item) }
(sugestão): Há formas padronizadas e bem mais elegante de serializar dados em API rails. Sugiro pesquisar sobre isso.

2021-05-05 20:10 UTC, ricardopacheco commented on front-end/nuxt.config.js
> +    baseURL: 'http://127.0.0.1:3000'
(refactor): Utilize variáveis de ambiente, traz bem mais flexibilidade.

2021-05-06 11:42 UTC, NaldoColella commented on back-end-api/app/controllers/municipes_controller.rb
> +    @municipes = checkPaginateParams(params) ? getPaginatedResults(params) : getAllResults()
Perfeito, estava assim antes, havia extraido em metodos privados para ajudar na legibilidade e ter um fallback para trazer tudo quando nao houvesse params, mas realmente nao tem essa necessidade. Vou ajustar

2021-05-06 11:54 UTC, italopires requested changes
Está ficando muito bom. Deixei apenas algumas sugestões para ajudar!

2021-05-06 11:54 UTC, italopires commented on back-end-api/app/controllers/municipes_controller.rb
> +      Municipe.page(params[:page]).per(params[:per_page])
Aqui você pode definir a quantidade default de itens por página, caso o params[:per_page] não venha por parâmetro.

`Municipe.page(params[:page]).per(params[:per_page] || 10)`

O operador `||` vai fazer com que se o lado esquerdo estiver `nil`, ele irá utilizar o lado direito `10`

2021-05-06 11:54 UTC, italopires commented on back-end-api/app/controllers/municipes_controller.rb
> +    def checkPaginateParams(params)
No ruby, o padrão de variáveis utilizado é o snakecase. Então aqui e em todos os outros pontos, você separaria por `_` as palavras da variável

2021-05-06 11:54 UTC, italopires commented on back-end-api/app/controllers/municipes_controller.rb
> +    render json: { items: serializeMunicipes(@municipes), totalCount: @totalMunicipes }
Você não precisa iterar os objetos para formar array de Serialize de Objetos. Você pode utilizar a propriedade `each_serializer: MunicipeSerializer`. Então ele vai resolver o teu problema quando tiver uma collection de objetos.

2021-05-06 12:06 UTC, italopires commented on front-end/nuxt.config.js
> +    baseURL: 'http://127.0.0.1:3000'
@NaldoColella dá uma olhada na gem dotenv-rails. Vai resolver teu problema quanto à variáveis de ambiente.

2021-05-06 12:06 UTC, gumiguelote commented on front-end/nuxt.config.js
> +    baseURL: 'http://127.0.0.1:3000'
https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#env-support

2021-05-06 12:29 UTC, NaldoColella commented on back-end-api/app/controllers/municipes_controller.rb
> +      Municipe.page(params[:page]).per(params[:per_page])
Perfeito, vou aplicar esses defaults

2021-05-06 18:31 UTC, merged